### ISSUE TITLE
CRU Data Visualizations

### ISSUE THREAD

**Issue by forestgeoadm** [forestgeo/Climate#28]
Hello, @teixeirak and @biancaglez,

I think that it would be helpful to add a section to the CRU README and/or to create a new README within the [figures/ForestGEO_sites_TS.plots.by.month folder](https://github.com/forestgeo/Climate/tree/master/Climate_Data/CRU/figures/ForestGEO_sites_TS.plots.by.month) to highlight and contextualize the data visualizations from the CRU data.  

I'm happy to work up a draft if you could confirm/correct the following information:

- @biancaglez created these figures in summer 2020 using [these scripts](https://github.com/forestgeo/Climate/tree/master/Climate_Data/CRU/scripts/CRU_viz_tool) based on CRU v4.04 data.  If data users should desire even more up-to-date figures, they could recreate them using the script, right?  

- I understand the 3 letter code between the plot name and "CRU" to indicate the variable that is illustrated, but what do the different plot designations within one field site mean?

- How shall we frame the intended use of these illustrations: to quickly identify trends?  to be used as supporting figures in a manuscript?  something else?

- Related to the above, what shall we say by way of data use and attribution?  Citation for original CRU data + attribution to @biancaglez ?  to ForestGEO Climate Data Portal?

Take care,
Caly

**Comment by biancaglez** [comment]
Hi Caly. 

> _@biancaglez created these figures in summer 2020 using these scripts based on CRU v4.04 data. If data users should desire even more up-to-date figures, they could recreate them using the script, right?_

--> Sort of. The plots won't update unless the data set is updated by the CRU data team and downloaded by us or interested users. The CRU dataset is updated every few years and has to be downloaded in a specific way using [these instructions and scripts](https://github.com/forestgeo/Climate/tree/master/Climate_Data/CRU/scripts/downloading_CRU_scripts). Currently we are using the most updated version. We will likely be updating the CRU data in the script, but it would be good to point them to where the CRU data lives in the repo -- so if we forget to update the link they know where to find it. Find the CRU [data here (currently version 4) ](https://github.com/forestgeo/Climate/tree/master/Climate_Data/CRU/CRU_v4_04)

Also-- If users would like to see an interactive plot (ie you can zoom in) then they can run the code and follow the instructions at the bottom of the script to see the interactive plot of interest (easier for users who know their way around R). 

> _I understand the 3 letter code between the plot name and "CRU" to indicate the variable that is illustrated, but what do the different plot designations within one field site mean?_

-->  A little confused by this. Do you mean what does the three-letter variable stand for? If so, point them to the read me at the beginning of the CRU repo f[ound here ](https://github.com/forestgeo/Climate/tree/master/Climate_Data/CRU)and or use this table to explain CRU variables 

Abbreviation | Description | Units
-- | -- | --
tmp | average daily mean temperatures | °C
tmn | average daily minimum temperatures | °C
tmx | average daily maximum temperatures | °C
drt | diurnal temperature range (i.e., temperature amplitude) | °C
frs | frost day frequency | days mo-1
pre | precipitation | mm mo-1
wet | wet day frequency | days mo-1
cld | cloud cover | %
vap | vapour pressure | hPa
pet | average daily potential evapotranspiration | mm day-1
pet_sum | potential evapotranspiration sum (computed here)

> _How shall we frame the intended use of these illustrations: to quickly identify trends? to be used as supporting figures in a manuscript? something else?_

I think quickly identifying trends is one important use. It helped us by quickly identifying which sites were filled with means. After seeing some sites were filled with means from ~1901-1920, we were able to write a script to identify the exact years that are filled with means. Find [that script here.](https://github.com/forestgeo/Climate/tree/master/Climate_Data/CRU/scripts/CRU_gaps_analysis) (and happy to write more about this if you're interested) ---- Not to mention, because the data is broken up by month, you can see the seasonality of the variables.

> _Related to the above, what shall we say by way of data use and attribution? Citation for original CRU data + attribution to @biancaglez ? to ForestGEO Climate Data Portal?_

My gut feeling is attribution to ForestGeo Climate Data Portal for the figures. For CRU data I would cite the CRU creators (found in readme of CRU page). @teixeirak will have better advice here.

**Comment by teixeirak** [comment]
All of what Bianca said is good. 

For attribution, they definitely need to cite CRU, and (as is the general policy), it would be best practice to mention that the data were retrieved from this site. 

I think its unlikely that someone would want to use the figures exactly as is in a publication; they'd more likely want to use @biancaglez 's script. If they do, they should cite the data portal. Note that Bianca will be on the author list for the data portal once we release on Zenodo (automatically generated based on contributions), so she'll get credit that way.  

I also think we should have a general mechanism to give specific attribution to people who have contributed code (this case) or data to the repository. This will be especially important if the person has send us data rather than directly contributing via GitHub. Recommended citation in this case would be "Figures were generated using a script by Bianca Gonzalez on the ForestGEO Climate Data Portal (*citation for data portal*)." I'd use a similar template for data sets, when a specific individual is identified. (This may get a bit complicated, in that these long-term data sets often have many contributors. For SCBI, for instance, I'd probably just leave a general citation to the data portal.)

**Comment by forestgeoadm** [comment]
Hi @biancaglez & @teixeirak,

Thank you for this feedback!

I've done my best to incorporate it into [this README](https://github.com/forestgeo/Climate/blob/master/Climate_Data/CRU/figures/ForestGEO_sites_TS.plots.by.month/A_README.MD).  If elements are missing (esp. re: the details of the scripts), please feel free to let me know or to go ahead and add them if you're inclined.

Oh, and I titled it "A_README" to get it to show up at the top of the list, but if you have a subtler way of doing that, please feel free to edit.

Take care,
Caly

P.S. I looked at the file names again and realized that the plot #s were just a way to keep track of all of the figures for a given site (as opposed to climate data for a sub-plot of the larger site).

**Comment by biancaglez** [comment]
I took a look and its simple and to the point. Thanks @forestgeoadm for the work :D
